# Generated by Django 3.0.5 on 2020-04-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('best_time', models.TextField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
